const SET_CLIENTS = 'SET_CLIENTS';
const SET_FEATURE_REQUESTS = 'SET_FEATURE_REQUESTS';
const ADD_FEATURE_REQUEST = 'ADD_FEATURE_REQUEST';

export {
  SET_CLIENTS,
  SET_FEATURE_REQUESTS,
  ADD_FEATURE_REQUEST,
};
